Botões para aprovar ou reprovar apólice
TreinaDev/insurance-app pull request #139
Opened 2022-11-20 20:02 UTC by manueladinizc

closes #136 
![status apolice](https://user-images.githubusercontent.com/101022596/202923500-347e1459-0d2f-4865-9d5f-bed0476a6032.PNG)

2022-11-21 21:24 UTC, RaphaellyV requested changes

2022-11-21 21:24 UTC, RaphaellyV commented on app/controllers/policies_controller.rb
>      @policy = Policy.find(params[:id])
Um funcionário de uma seguradora consegue acessar a página de detalhes da apólice de outra seguradora e alterar seu status. Precisamos de um teste de sistema e de um de request para barrar isso, redirecionando o usuário para outra tela e mostrando uma mensagem.

2022-11-21 21:24 UTC, RaphaellyV commented on config/locales/models/policies.pt-BR.yml
> +        pending_payment: 'Pagamento Pendente'
Vocês adicionaram a tradução "Pagamento Pendente" em dois lugares?

2022-11-21 21:24 UTC, RaphaellyV commented on spec/system/policy/user_changes_policy_status_spec.rb
> +end
Aqui poderia ter os testes de falha, como mencionei antes: para que um funcionário de outra empresa não consiga acessar os dados de uma apólice de outra empresa, nem tenha acesso aos botões.

2022-11-21 21:24 UTC, RaphaellyV commented on spec/system/policy/user_view_pending_payment_policies_spec.rb
> +describe 'Administrador vê lista de apólices com pagemento pendente' do
pagamento pendente*

2022-11-21 21:30 UTC, AnitaLuri submitted a review, later dismissed

2022-11-21 21:30 UTC, AnitaLuri commented on app/controllers/policies_controller.rb
>      @policy = Policy.find(params[:id])
Concordo com a Rapha!

2022-11-22 02:59 UTC, RaphaellyV commented on app/controllers/policies_controller.rb
> +    @order_id = @policy.order_id
Não entendi o propósito dessa variável @order_id...

2022-11-22 03:19 UTC, RaphaellyV requested changes

2022-11-22 03:19 UTC, RaphaellyV commented on config/locales/models/policies.pt-BR.yml
> -      policy/status:
Essa forma de tradução aqui que é a correta, eu acho... No show da apólice, está aparecendo "Ativo" ao invés de "Ativa", como deveria, então não sei de onde está sendo puxada essa tradução, mas daqui não parece ser. Percebi que na view show, a chamada para esse atributo está diferente da que normalmente uso: Package.human_attribute_name("status.#{@package.status}")

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_view_active_policy_list_spec.rb
>                                price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_view_all_policy_list_spec.rb
>                                price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/requests/policies/user_view_policy_spec.rb
> +                              price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_changes_policy_status_spec.rb
> +                                price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_changes_policy_status_spec.rb
> +                                price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_changes_policy_status_spec.rb
> +                               price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_changes_policy_status_spec.rb
> +                               price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_view_canceled_policy_list_spec.rb
>                                price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_view_pending_payment_policies_spec.rb
>                                price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_view_pending_policy_list_spec.rb
>                                price: 90.00, product_category_id: product_category.id)
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_view_policy_details_spec.rb
> +                              insurance_company_id: insurance_company.id, price: 90.00,
Preço do pacote é percentual

2022-11-22 03:19 UTC, RaphaellyV commented on spec/system/policy/user_view_policy_details_spec.rb
> +                              insurance_company_id: insurance_company.id, price: 90.00,
Preço do pacote é percentual

2022-11-22 12:40 UTC, RaphaellyV approved these changes

2022-11-22 12:42 UTC, merged