Administrador ativa e desativa serviço e cobertura
TreinaDev/insurance-app pull request #156
Opened 2022-11-23 22:25 UTC by an-finocchiaro

2022-11-24 12:50 UTC, joaorsalmeida requested changes
Me parece que faltou tratar o controle de quem pode ativar/desativar coberturas? Só Admins? O único teste que vi era pra ver se tinha alguém logado mas seria legal validar quem está logado (admin ou user de seguradora?)

2022-11-24 12:50 UTC, joaorsalmeida commented on app/controllers/package_coverages_controller.rb
> +  def activate
Qualquer usuário vai poder fazer essas ações?

2022-11-24 13:54 UTC, adboza approved these changes

2022-11-25 17:48 UTC, joaorsalmeida approved these changes

2022-11-25 18:07 UTC, merged