Cadastra categoria
TreinaDev/insurance-app pull request #46
Opened 2022-11-04 14:00 UTC by adboza

Incluído index, new, create para categoria de produto.
Issue: #1 
Issue irá para blocked para após merge resolver próximos testes descritos na tarefa.
Co-Authored-By: Andrea <andrea.amnaya@gmail.com>

2022-11-04 14:42 UTC, joaorsalmeida commented on spec/models/product_category_spec.rb
> +    end
Mantenham sempre uma linha em branco de um cenário para o outro. Tudo 'grudado' assim dificulta muito a leitura.

2022-11-04 14:43 UTC, joaorsalmeida commented on spec/system/product/user_view_product_list_spec.rb
> +    #Arrange
No começo usávamos esses comentários para aprendizado. Acredito que já podemos removê-los e usar somente linhas em branco para separar os 3 blocos dentro de cada teste :)

2022-11-04 14:43 UTC, joaorsalmeida commented on app/controllers/product_categories_controller.rb
> +     redirect_to product_categories_path, notice:'Categoria de produto cadastrada com sucesso!'
Cuidado com a formatação. Poderia ter um espaço em branco depois de `notice:`

2022-11-04 14:44 UTC, joaorsalmeida reviewed
Parece tudo ok, mas fiz alguns comentários pensando na legibilidade do código. Podem verificar?

2022-11-04 14:44 UTC, joaorsalmeida commented on app/controllers/products_controller.rb
> +class ProductsController < ApplicationController
Esse código não parece ser dessa tarefa 🤔

2022-11-07 13:52 UTC, joaorsalmeida commented on .rubocop.yml
> +    - 'spec/models/*'
Nao podemos remover os testes do `Rubocop`

2022-11-07 13:55 UTC, joaorsalmeida requested changes
Me parece bem encaminhado mas peço que revisem os comentários que fiz.

2022-11-07 13:55 UTC, joaorsalmeida commented on .rubocop.yml
> +    - 'app/models/product_category.rb'
Não podemos remover os models também.

2022-11-07 13:55 UTC, joaorsalmeida commented on .rubocop.yml
> +  Enabled: False
Essa é uma cop que costuma ser habilitada. Algum motivo pra desabilitar? Foi discutido por toda equipe?

2022-11-07 14:57 UTC, adboza commented on .rubocop.yml
> +  Enabled: False
O motivo para desabilitar é que para quem está programando com windows existe um bug. Para passar o rubocop eu criei os arquivos novamente no linux, copiei e colei o conteúdo deles exatamente igual, e deletei o arquivo criado no windows. Segue um forum de discussão. https://github.com/rubocop/rubocop/issues/3401 .

2022-11-08 18:35 UTC, joaorsalmeida approved these changes
Me parece tudo certo!

2022-11-08 18:37 UTC, merged