Adm ve lista seguradoras
TreinaDev/insurance-app pull request #60
Opened 2022-11-08 00:44 UTC by manueladinizc

#16 
Co-authored-by: Sarah <sarahsantosst@gmail.com>
![seguradoras](https://user-images.githubusercontent.com/101022596/200446120-01b5d36d-babc-45fb-87ad-061118b81d83.PNG)

2022-11-08 15:47 UTC, joaorsalmeida requested changes
Turma, não entendi algumas coisas, se puderem explicar um pouco (ou revistar mesmo o código).

2022-11-08 15:47 UTC, joaorsalmeida commented on app/controllers/insurance_companies_controller.rb
> +    @insurance_companies = InsuranceCompany.all.filter { |insurance| insurance.email_domain != 'empresa.com.br' }
Não entendi esse filtro

Vão existir Admins vinculados à seguradoras? Me parece desnecessário.

2022-11-08 15:47 UTC, joaorsalmeida commented on app/models/insurance_company.rb
> +  def generate_token
Esse método não é chamado nunca?

2022-11-08 15:47 UTC, joaorsalmeida commented on spec/system/insurance_company/user_view_isurance_list_spec.rb
> +  it 'e não possui acesso a essa página' do
Realmente não entendi esse cenário. Não faz sentido pra mim um admin vinculado à uma seguradora.

2022-11-08 17:06 UTC, manueladinizc commented on app/controllers/insurance_companies_controller.rb
> +    @insurance_companies = InsuranceCompany.all.filter { |insurance| insurance.email_domain != 'empresa.com.br' }
O filtro foi criado pq o model users tem uma seguradora atrelada ao usuário, e como ela tá como obrigatória, o usuário administrador tbm precisaria ter uma (pelo menos por enquanto), mas como não queremos que a empresa principal apareça na lista de seguradoras, fizemos esse filtro

2022-11-08 17:06 UTC, manueladinizc commented on app/models/insurance_company.rb
> +  def generate_token
Realizei a correção

2022-11-08 17:09 UTC, manueladinizc commented on spec/system/insurance_company/user_view_isurance_list_spec.rb
> +  it 'e não possui acesso a essa página' do
Percebi que existiam inconsistências nos testes. Fiz uma revisão. O admin será atrelado a uma Empresa padrão (não será uma seguradora), para que seja possível logar na aplicação. Complementando a explicação sobre o filtro aplicado.

2022-11-08 18:37 UTC, joaorsalmeida commented on app/controllers/insurance_companies_controller.rb
> +    @insurance_companies = InsuranceCompany.all.filter { |insurance| insurance.email_domain != 'empresa.com.br' }
Vocês poderiam deixar a seguradora opcional com a opção `optional: true` do `belongs_to`

https://guides.rubyonrails.org/association_basics.html#optional

Daí poderia ter uma validação personalizada no User que verifica se ele é admin e neste caso permite que a seguradora seja vazia. Caso nao seja admin a seguradora deve estar preenchida.

2022-11-08 18:38 UTC, joaorsalmeida commented on app/models/insurance_company.rb
> +  def generate_token
Me preocupa só esse código aqui não ter teste unitário né?! Podemos fazer nessa branch? Senão abram uma issue nova pra registrar que falta fazer este teste.

2022-11-08 19:42 UTC, joaorsalmeida commented on spec/system/insurance_company/user_view_isurance_list_spec.rb
> +  it 'e não possui acesso a essa página' do
Ao invés de empresa padrão, nao poderíamos usar o `opcional` como citei e deixar o admin sem empresa?

2022-11-09 18:25 UTC, joaorsalmeida commented
@manueladinizc e @sarahsantosst como está esse PR? Posso revisar novamente?

2022-11-09 18:38 UTC, manueladinizc commented
@joaorsalmeida Houve alguns conflitos, vamos abrir uma issue para desvincular o admin da seguradora.  Avisamos no mattermost quando estiver revisado.

2022-11-10 00:05 UTC, manueladinizc commented on app/controllers/insurance_companies_controller.rb
> +    @insurance_companies = InsuranceCompany.all.filter { |insurance| insurance.email_domain != 'empresa.com.br' }
Aplicamos a sugestão de vincular como [optional](optional: true do belongs_to)

2022-11-10 00:06 UTC, manueladinizc commented on app/models/insurance_company.rb
> +  def generate_token
Acabei deixando passar, mas abri a issue #75 para fazer o teste unitário

2022-11-10 00:07 UTC, manueladinizc commented on spec/system/insurance_company/user_view_isurance_list_spec.rb
> +  it 'e não possui acesso a essa página' do
Aplicamos a sugestão de optional: true

2022-11-10 00:15 UTC, manueladinizc commented
#16 
#67 
![layout seguradoras](https://user-images.githubusercontent.com/101022596/200969277-288c5bd6-f591-47d1-ab34-ffaf030ef243.PNG)

2022-11-10 13:42 UTC, joaorsalmeida approved these changes
Aprovado mas com uma pequena sugestão

2022-11-10 13:42 UTC, joaorsalmeida commented on app/models/user.rb
> +    self.insurance_company = InsuranceCompany.find_by(email_domain: email.partition('@').last) if admin? == false
Ao invés de `if admin? == false` que tal usar `if employee?`

2022-11-10 13:42 UTC, joaorsalmeida commented on app/controllers/insurance_companies_controller.rb
> +    @insurance_companies = InsuranceCompany.all
❤️

2022-11-10 14:15 UTC, merged